media:
  input: static/images
  output: /images
content:
  #--------------------
  #  Jobs
  #--------------------
  - name: jobs
    label: Jobs
    path: content/jobs
    filename: index.en.md
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: description_long
        label: Meta Description
        type: text
        description: "Short description of the job post. It will be used for schema.org and og:description."
      - name: description_short
        label: Description Short
        type: rich-text
        options:
          format: html
          image:
            path: static/
            extensions: [ jpg, jpeg, png ]
      - name: published_date
        label: Published Date
        type: date
      - name: modified_date
        label: Modified Date
        type: date
        hidden: true
      - name: draft
        label: Draft
        type: boolean
      - name: type
        label: Type
        type: string
        hidden: true
        default: job
  #--------------------
  #  Products
  #--------------------
  - name: products
    label: Products
    path: data
    filename: products.yml
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: meta_description
        label: Description
        type: text
      - name: product_description
        label: Product Description
        type: rich-text
        options:
          format: html
