media:
  input: static/images
  output: /images
content:
  #--------------------
  #  Jobs
  #--------------------
  - name: jobs
    label: Jobs
    path: content/jobs
    filename: index.en.md
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description_long
        label: Meta Description
        type: text
        description: "Short description of the job post. It will be used for schema.org and og:description."
        required: true


      - name: product
        label: Description
        type: rich-text
        options:
          format: html

      - name: published_date
        label: Published Date
        type: date
        required: true
      - name: modified_date
        label: Modified Date
        type: date
        hidden: true
      - name: draft
        label: Draft
        type: boolean
      - name: type
        label: Type
        type: string
        hidden: true
        default: job